// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToTradeHistory(arg1) {
  return window['go']['main']['App']['AddToTradeHistory'](arg1);
}

export function AddToTradeQueue(arg1) {
  return window['go']['main']['App']['AddToTradeQueue'](arg1);
}

export function AttemptReconnect(arg1, arg2, arg3) {
  return window['go']['main']['App']['AttemptReconnect'](arg1, arg2, arg3);
}

export function DisableAllProtocols(arg1) {
  return window['go']['main']['App']['DisableAllProtocols'](arg1);
}

export function GetHedgeSize() {
  return window['go']['main']['App']['GetHedgeSize']();
}

export function GetNetPosition() {
  return window['go']['main']['App']['GetNetPosition']();
}

export function GetQueueSize() {
  return window['go']['main']['App']['GetQueueSize']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTradeHistory() {
  return window['go']['main']['App']['GetTradeHistory']();
}

export function GetTradeQueue() {
  return window['go']['main']['App']['GetTradeQueue']();
}

export function HandleCloseHedgeRequest(arg1) {
  return window['go']['main']['App']['HandleCloseHedgeRequest'](arg1);
}

export function HandleElasticUpdate(arg1) {
  return window['go']['main']['App']['HandleElasticUpdate'](arg1);
}

export function HandleHedgeCloseNotification(arg1) {
  return window['go']['main']['App']['HandleHedgeCloseNotification'](arg1);
}

export function HandleMT5TradeResult(arg1) {
  return window['go']['main']['App']['HandleMT5TradeResult'](arg1);
}

export function HandleTrailingStopUpdate(arg1) {
  return window['go']['main']['App']['HandleTrailingStopUpdate'](arg1);
}

export function IsAddonConnected() {
  return window['go']['main']['App']['IsAddonConnected']();
}

export function IsHedgebotActive() {
  return window['go']['main']['App']['IsHedgebotActive']();
}

export function PollTradeFromQueue() {
  return window['go']['main']['App']['PollTradeFromQueue']();
}

export function SetAddonConnected(arg1) {
  return window['go']['main']['App']['SetAddonConnected'](arg1);
}

export function SetHedgebotActive(arg1) {
  return window['go']['main']['App']['SetHedgebotActive'](arg1);
}
