// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddToTradeHistory(arg1:any):Promise<void>;

export function AddToTradeQueue(arg1:any):Promise<void>;

export function AttemptReconnect(arg1:boolean,arg2:boolean,arg3:boolean):Promise<Record<string, any>>;

export function DisableAllProtocols(arg1:Array<string>):Promise<void>;

export function GetHedgeSize():Promise<number>;

export function GetNetPosition():Promise<number>;

export function GetQueueSize():Promise<number>;

export function GetStatus():Promise<Record<string, any>>;

export function GetTradeHistory():Promise<Array<main.Trade>>;

export function GetTradeQueue():Promise<any>;

export function HandleElasticUpdate(arg1:any):Promise<void>;

export function HandleHedgeCloseNotification(arg1:any):Promise<void>;

export function HandleMT5TradeResult(arg1:any):Promise<void>;

export function HandleCloseHedgeRequest(arg1:any):Promise<void>;

export function HandleTrailingStopUpdate(arg1:any):Promise<void>;

export function IsAddonConnected():Promise<boolean>;

export function IsHedgebotActive():Promise<boolean>;

export function PollTradeFromQueue():Promise<any>;

export function SetAddonConnected(arg1:boolean):Promise<void>;

export function SetHedgebotActive(arg1:boolean):Promise<void>;
